name: Les Imgrund Photography
favicon: null
layout_spectrum: 0.07175202015787363
typography_spectrum: 0.11072621820494533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.16588100930675864
  lightness: 0.12497495906427503
  saturation: 0.613615594804287
  rhythmicContrast: 0.37843204755336046
purpose: []
