name: Les Imgrund Photography
favicon: null
layout_spectrum: 0.23392123263329268
typography_spectrum: 0.39874854520894587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.29013976152054965
  lightness: 0.6679205724503845
  saturation: 0.7585716615431011
  rhythmicContrast: 0.35640492965467274
purpose: []
